# Introduction to TensorFlow
--------
 * What is Tensorflow ?
 * What is Tensor ?
 * Computational graph
 * Variable
 * Placeholder
 * Operation

### 1. What is Tensorflow ?
   TensorFlow is open source Machine Learning library introduced by Google in 2015. Initially it was made for Google internal use by Google Brain team but in 2015 it has made open source. It is a high performance computation library and heavily used by the developers and researchers throughout the world.It has very flexible architecture which allows easy deployment of computation across a variety of platforms CPUs, GPUs, TPUs and from desktops to clusters of servers to mobile and edge devices.<br>
   It is written in python ,c++ and cuda that is why its numerical computation is fast.

### 2. What is Tensor ?

Tensorflow uses Tensor to make its computational graph.Only tensors are passed between operations in the computation graph. You can think of a TensorFlow tensor as an n-dimensional array or list.
![](Tensor.jpeg)

### 3. Computational Graph

Tensorflow uses computational graph to executes its operation.To execute these operations as computations, we must launch the Graph into a Session. The session translates and passes the operations represented into the graphs to the device you want to execute them on GPU or CPU.<br>
For example, the image below represents a graph in TensorFlow. a and b can be any number/array/matrix/tensors over the edges of this graph. Add(+) is an operation over the variables a  and b, after that Add is called and multiply the result of the previous operator with 3. The resultant of each operation across the next one until the end where it's possible to get the wanted result.
![](cg.png)


Now the question arises how to create a computational graph/ dataflow graph in tensorflow?

   **Think of the simple python script** <br>
   If i ask you store two numbers in variables 'a' and 'b', then add these number and store it into variable 'c'. Now multiply 'c' with any number m and store it in 'd'. Then print 'd'.This is same as described in the above image.
   

In [2]:
a=3
b=4
c= a+b
d= c*3
print(d)

14


This can be done in Tensorflow with computational graph as follows -
  * First import the Tensorflow
  * Store the values in different variables
  * Initialised the session() to execute the graph 
  * Execute the graph <br>
**Note :** Want to know more about Session and dataflow graph click on this [link](https://medium.com/coinmonks/tensorflow-graphs-and-sessions-c7fa116209db)

In [4]:
import tensorflow as tf

tf.constant is used to initialised any variable with constant number.

In [32]:
a=tf.constant(3)   # a=3
b=tf.constant(4)   # b=4
c=tf.add(a,b)      # c= a+b
d=c*3              # d= c*3

Then Tensorflow needs to initialize a session to run the code. Session is a way to create computational graph

In [33]:
### Initialising session
sess = tf.Session() 

Now run the Session() to get the result from dataflow graph

In [34]:
result = sess.run(d)
print(result)

21


Then close the Session to release the all resourses.

In [35]:
sess.close()

This looks a tedious to close the session every time, so here is another way. Initialize session a __with__ block then i will automatically closed you dont need to close it.

In [39]:
with tf.Session() as sess:
    result=sess.run(d)
    print(result)

21


#### Types of Tensors :
* Scalar( Any number)
* Vector(Any 1D array)
* Matrix(Any 2D array)
* Multi-dimensional array

In [42]:
# Scalar
A=tf.constant(5)
# Vector
B=tf.constant([1,2,3,4])
# Matrix 
C=tf.constant([[1,2,3],[4,5,6],[7,8,9]])
# Multi-dimensional array
D=tf.constant([[[1,2,3],[2,3,4],[3,4,5]],[[4,5,6],[5,6,7],[6,7,8]],[[7,8,9],[8,9,10],[9,10,11]]])

In [44]:
print("Types of Tensors")
with tf.Session() as sess:
    result=sess.run(A)
    print("Scalar :\n ",result)
    result=sess.run(B)
    print("Vector : \n",result)
    result=sess.run(C)
    print("Matrix :\n ",result)
    result=sess.run(D)
    print("Multi-dimensional array :\n ",result)

Types of Tensors
Scalar :
  5
Vector : 
 [1 2 3 4]
Matrix :
  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Multi-dimensional array :
  [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]]


### 4. Variables

Now that we are more familiar with the structure of data, we will take a look at how TensorFlow handles variables.

To define variables we use the command __tf.variable()__. To be able to use variables in a computation graph it is necessary to initialize them before running the graph in a session. This is done by running __tf.global_variables_initializer()__.

To update the value of a variable, we simply run an assign operation that assigns a value to the variable:

In [54]:
var = tf.Variable(0)

Let's first create a simple counter, a variable that increases one unit at a time:

In [55]:
i = tf.constant(1)
new_var = tf.add(var,i)
update = tf.assign(var, new_var)

We must be initialised the variable before running the session. Then we first add the initialisation operation to the graph.

In [57]:
init_var = tf.global_variables_initializer()

We then start a session to run the graph, first initialize the variables, then print the initial value of the __var__ variable, and then run the operation of updating the __var__ variable and printing the result after each update:

In [62]:
with tf.Session() as sess:
    sess.run(init_var)
    print("Initial var :\n",sess.run(var))
    print("Printing after updating var in each iteration : ")
    for _ in range(5):
        sess.run(update)
        print(sess.run(var))

Initial var :
 0
Printing after updating var in each iteration : 
1
2
3
4
5


### 5. Placeholders

Now we know how to manipulate variables inside TensorFlow, but what about feeding data outside of a TensorFlow model? 

If you want to feed data to a TensorFlow model from outside a model, you will need to use placeholders.

So what are these placeholders and what do they do? 

Placeholders can be seen as "holes" in your model, "holes" which you will pass the data to, you can create them using <br/> <b>tf.placeholder(_datatype_)</b>, where <b>_datatype_</b> specifies the type of data (integers, floating points, strings, booleans) along with its precision (8, 16, 32, 64) bits.

The definition of each data type with the respective python sintax is defined as: <br>
![](datatype.png)
<br>
**Let's create a placeholder ,**

In [63]:
a = tf.placeholder(tf.float32)

**And define a simple multiplication operation:**

In [64]:
b = a*2

Now we need to define and run the session, but since we created a "hole" in the model to pass the data, when we initialize the session we are obligated to pass an argument with the data, otherwise we would get an error.

To pass the data to the model we call the session with an extra argument <b> feed_dict</b> in which we should pass a dictionary with each placeholder name folowed by its respective data, just like this:

In [65]:
with tf.Session() as sess:
    result = sess.run(b,feed_dict={a:3.5})
    print (result)

7.0


Since data in TensorFlow is passed in form of multidimensional arrays we can pass any kind of tensor through the placeholders to get the answer to the simple multiplication operation:

In [66]:
dictionary={a: [ [ [1,2,3],[4,5,6],[7,8,9],[10,11,12] ] , [ [13,14,15],[16,17,18],[19,20,21],[22,23,24] ] ] }

with tf.Session() as sess:
    result = sess.run(b,feed_dict=dictionary)
    print (result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


Now you can observe that Tensor in the disctionary is get multiplied by 2.In the same way what ever Tensor you put in the disctionary it be multiplied by 2 in this case.

### 6. Operations 

Operations are nodes that represent the mathematical operations over the tensors on a graph. These operations can be any kind of functions, like add and subtract tensor or maybe an activation function.

_tf.matmul_, _tf.add_, _tf.nn.sigmoid_ are some of the operations in TensorFlow. These are like functions in python but operate directly over tensors and each one does a specific thing. 
<div class="alert alert-success alertsuccess" style="margin-top: 20px">Other operations can be easily found in: https://www.tensorflow.org/versions/r0.9/api_docs/python/index.html</div>
<br>
Few examples are as follows:
<br>
#### tf.add(), tf.matmul() and tf.subtract()
* tf.add() is always used to add two tensors of same dimensions.
* tf.matmul() is always used to multiply two square matrix of same dimensions.
* tf.subtract is used to subtract two Tensors.

In [67]:
A=tf.constant([[1,2],[1,2]])
B=tf.constant([[3,2],[3,2]])
addition=tf.add(A,B)
subtraction=tf.subtract(A,B)
multiplication=tf.matmul(A,B)
with tf.Session() as sess:
    result=sess.run(addition)
    print("Addition result : \n",result)
    result=sess.run(subtraction)
    print("Subtraction result : \n",result)
    result=sess.run(multiplication)
    print("Multiplication result : \n ",result)
    

Addition result : 
 [[4 4]
 [4 4]]
Subtraction result : 
 [[-2  0]
 [-2  0]]
Multiplication result : 
  [[9 6]
 [9 6]]


### Conclusion 

Now you have a much better understanding of tensors, the types of data that fit in them and how handle various tensors operations using dataflow/computation graph. In the next blog i will talk about how we can apply these concept to make our Machine Learning or Deep Learning models.